// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3yMHZS-wP2d4kbb-HZ4i_fNEe56jWGFw',
    appId: '1:950508003260:web:2e7097c1608dc44f1555b9',
    messagingSenderId: '950508003260',
    projectId: 'face-auth-c1a52',
    authDomain: 'face-auth-c1a52.firebaseapp.com',
    storageBucket: 'face-auth-c1a52.appspot.com',
    measurementId: 'G-L60P206E2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNzT9qx4hJrlvF5fZIgSrYJi__KmNa5dQ',
    appId: '1:950508003260:android:7f4d8f57f971648d1555b9',
    messagingSenderId: '950508003260',
    projectId: 'face-auth-c1a52',
    storageBucket: 'face-auth-c1a52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe3z5t3C_BKPkuEbOdJyOjUneHG-5HBfc',
    appId: '1:950508003260:ios:dd365b859409fa9d1555b9',
    messagingSenderId: '950508003260',
    projectId: 'face-auth-c1a52',
    storageBucket: 'face-auth-c1a52.appspot.com',
    iosClientId: '950508003260-8k0r01m37grcqgeka3rbnoj6ibllhmrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe3z5t3C_BKPkuEbOdJyOjUneHG-5HBfc',
    appId: '1:950508003260:ios:dd365b859409fa9d1555b9',
    messagingSenderId: '950508003260',
    projectId: 'face-auth-c1a52',
    storageBucket: 'face-auth-c1a52.appspot.com',
    iosClientId: '950508003260-8k0r01m37grcqgeka3rbnoj6ibllhmrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceAuth',
  );
}
